### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by qiyan98** [KarolisMart/SPECTRE#1]
Hi there,

Thanks for open-sourcing your code for the wonderful project. I ran into an issue when trying to run your code as instructed.
For example, when trying to run training on planar data like this:
```
python full_gan.py --batch_size 10 --max_epochs=12000 --log_every_n_steps=60 --check_val_every_n_epoch 90 --gen_gelu --disc_gelu --k_eigval 2 --eigvec_temp_decay --decay_eigvec_temp_over 2000 --min_eigvec_temp 0.8 --n_eigval_warmup_epochs 2000 --n_eigvec_warmup_epochs 2000 --eigval_temp_decay --decay_eigval_temp_over 2000 --min_eigval_temp 0.8 --SON_D_full_readout --noisy_gen --SON_normalize_left --lambda_gating --lambda_last_gating --lambda_upsample --SON_small --noisy_disc --derived_eigval_noise --normalize_noise --spectral_norm --eigvec_right_noise --gp_shared_alpha --no_restart --SON_gumbel_temperature_decay --decay_SON_gumbel_temp_over 10000 --SON_gumbel_temperature_warmup_epochs 0 --n_data_workers 4 --dataset planar --n_nodes 64 --gp_do_backwards --eigvec_sign_flip --ignore_first_eigv --gp_include_unpermuted --clip_grad_norm 1.0 --seed 0
```

I got the error `AttributeError: 'GraphDataModule' object has no attribute 'train_mmd_wavelet'`. Using single-GPU and dual-GPUs lead to the same error. I think this line is wrong inside the [`full_gan.py`](https://github.com/KarolisMart/SPECTRE/blob/5add03b9a3a4e694d8295a36826c681e80aff037/full_gan.py)
https://github.com/KarolisMart/SPECTRE/blob/5add03b9a3a4e694d8295a36826c681e80aff037/full_gan.py#L1718

But your code is highly-coupled and complex. I am not sure what is the best way to fix this bug. I'd appreciate it if you could provide some help.

Best,
Qi

**Comment by KarolisMart** [comment]
Hi Qi,

Thanks for pointing this out. Seems that when I did a quick variable name change before the initial commit I failed to do it everywhere. It should work now. 
Let me know if you run into any other problems.

Best,
Karolis

**Comment by qiyan98** [comment]
Hi Karolis,

Thanks for your quick feedback! The problem is sovled. :)

Best,
Qi

**Comment by KarolisMart** [comment]
Great!
