### ISSUE TITLE
May I have the code for generating the sbm dataset?

### ISSUE THREAD

**Issue by Xiaohui9607** [KarolisMart/SPECTRE#2]
Is it okay to share the code for generating the sbm dataset? thx!

**Comment by KarolisMart** [comment]
Sure. We use the standard NetworkX routine for this: https://github.com/KarolisMart/SPECTRE/blob/main/data.py#L233 
The dataset file would also automatically re-generate (if it was deleted) when running the training command 
`python full_gan.py --batch_size 5 --max_epochs=6000 --log_every_n_steps=60 --check_val_every_n_epoch 45 --gen_gelu --disc_gelu --k_eigval 4 --eigvec_temp_decay --decay_eigvec_temp_over 1000 --min_eigvec_temp 0.8 --n_eigval_warmup_epochs 1000 --n_eigvec_warmup_epochs 1000 --eigval_temp_decay --decay_eigval_temp_over 1000 --min_eigval_temp 0.8 --SON_D_full_readout --noisy_gen --SON_normalize_left --lambda_gating --lambda_last_gating --lambda_upsample --SON_small --noisy_disc --derived_eigval_noise --normalize_noise --spectral_norm --eigvec_right_noise --gp_shared_alpha --no_restart --SON_gumbel_temperature_decay --decay_SON_gumbel_temp_over 5000 --SON_gumbel_temperature_warmup_epochs 0 --n_data_workers 4 --dataset sbm --gp_do_backwards --eigvec_sign_flip --ignore_first_eigv --gp_include_unpermuted --clip_grad_norm 1.0`

**Comment by Xiaohui9607** [comment]
Thx!
